MyStatus/config/routes.rb
Rails.application.routes.draw do
  resources :statuses do
    resources :comments
  end

  resources :users 
  resources :friends
  get 'sessions' => 'sessions#create', as: :create

  get 'sessions/destroy'

  get 'login' => 'sessions#new'

  get 'logout' => 'sessions#destroy'

  get 'info' => 'users#show'


  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'about' => 'pages#about', as: :about
  get 'contact' => 'pages#contact', as: :contact
  get 'register' => 'users#new', as: :register
  root 'statuses#new'
  
  resources :sessions, only: [:new, :create, :destroy]
end

MyStatus/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MyStatus/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :status
  belongs_to :user
end

MyStatus/app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
	belongs_to :friend, :class_name => 'User'
end

MyStatus/app/models/status.rb
class Status < ApplicationRecord
	belongs_to :user
	has_many :comments
	validates :content, presence: true
end

MyStatus/app/models/user.rb
class User < ApplicationRecord
	has_many :status

	has_many :friends
	has_many :friends_users, :through => :friends

end

MyStatus/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authorize
	def current_user
		@users ||= User.find(session[:current_user_id]) if session[:current_user_id]
	end

	def authorize
		unless current_user
			redirect_to '/login'
		end
	end
end

MyStatus/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_comment, only: [:edit, :destroy]
    before_action :authorize
    def create
        @status = Status.find(params[:status_id])
        @comment = @status.comments.new(comment_params)
        @comment.user_id= current_user.id
        @comment.save
        redirect_to "/"
    end

    def destroy
        @status = Status.find(params[:status_id])
        @comment = @status.comments.find(params[:id])
        @comment.destroy
        respond_to do |format|
            format.html { redirect_to new_status_path }
            format.json { head :no_content }
        end
    end

    private
    def set_comment
        @comment=Comment.find(params[:id])
    end
    def comment_params
      	params.require(:comment).permit(:body, :user_id, :status_id)
    end
end

MyStatus/app/controllers/friends_controller.rb
class FriendsController < ApplicationController
	before_action :authorize
	def index
		@user = User.find(session[:current_user_id])
	end

	def create
		user = User.find(session[:current_user_id])
		@friends = user.friends.build(:friend_id => params[:friend_id])
    	@friends.save

    	user = User.find(params[:friend_id])
    	@inverse_friend = user.friends.build(:friend_id => session[:current_user_id])
    	@inverse_friend.save

		redirect_to :back
	end

	def destroy
		user = User.find(session[:current_user_id])
		@friendship = user.friends.find_by_friend_id(params[:id])
  		@friendship.destroy

  		user = User.find(params[:id])
		@friendship = user.friends.find_by_friend_id(session[:current_user_id])
  		@friendship.destroy
  		
		redirect_to :back
	end

end

MyStatus/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def about
	end

	def contact
	end
end

MyStatus/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :authorize, except: [:new, :create]
	def new
	end

	def create
		@users = User.find_by(Username: params[:Username])
		if @users and User.find_by(Password: params[:Password])
			session[:current_user_id] = @users.id
			redirect_to root_path
		else
			render :new
		end
	end

	def destroy
		session[:current_user_id]= nil;
		redirect_to root_path
	end
end

MyStatus/app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @statuses = Status.joins("INNER JOIN friends ON friends.friend_id = statuses.user_id AND friends.user_id like '%#{session[:current_user_id]}%'").order('statuses.created_at desc')
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)
    @status.user_id= current_user.id
    respond_to do |format|
      if @status.save
        format.html { redirect_to :back, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to "/", notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to "/", notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:content, :user_id)
    end
end

MyStatus/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def authorize
    unless current_user
      redirect_to '/login'
    end
  end

  def index
    if params[:search].present?
      @users = User.where("Username like? or Name like?", "%#{params[:search]}%", "%#{params[:search]}%")
    else
      @users = User.all
    end
  end
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        session[:current_user_id]= @user.id
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

    @friends = @user.friends.build(:friend_id => session[:current_user_id])
    @friends.save
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      if(params[:id] == nil)
        @user = User.find(session[:current_user_id])
      else
        @user = User.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:Username, :Name, :Password, :birth, :from, :work_at, :avatar)
    end
end

MyStatus/app/helpers/application_helper.rb
module ApplicationHelper
end

MyStatus/app/helpers/comments_helper.rb
module CommentsHelper
end

MyStatus/app/helpers/friends_helper.rb
module FriendsHelper
end

MyStatus/app/helpers/pages_helper.rb
module PagesHelper
end

MyStatus/app/helpers/sessions_helper.rb
module SessionsHelper
end

MyStatus/app/helpers/statuses_helper.rb
module StatusesHelper
end

MyStatus/app/helpers/users_helper.rb
module UsersHelper
end

MyStatus/app/views/friends/index.html.erb
<% for user in @user.friends%>
<% @temp = User.find_by_id(user.friend_id)%>
<% if (@temp!=nil) and (user.friend_id != session[:current_user_id]) %>
  <div class="row card" style="margin-left: 150px; margin-right: 150px;">
        <div class="container" style="margin-bottom: -10px; padding-top: 25px;">
        <div class="col-sm-1">
          <div class="text-xs-center"><img src="<%= @temp.avatar%>" class="img-circle" width="50" height="50"></div>
        </div>
        <div class="col-sm-11">
          <div ><%= @temp.Username %></div>
          <div ><%= @temp.Name %></div>
          <p class="pull-xs-right" style="margin-right: 5px; margin-bottom: 5px;">
            <%= link_to 'Info', @temp, class: 'btn btn-success', style: 'padding: 2px 10px;' %>
            <%= link_to 'Unfriend', {controller: "friends", action: "destroy", id: @temp.id}, method: "delete", class: 'btn btn-danger', style: 'padding: 2px 10px;' %>
          </p>
        </div> 
    </div>
  </div>
<% end %>
<% end %>

MyStatus/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | MyStatus</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    </style>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-inverse">
      <div class="nav navbar-nav list-group list-group-flush">
        <%= link_to 'Home', root_path, class: "nav-item nav-link " %>
        <%= link_to 'About', about_path, class: "nav-item nav-link #{yield(:about_active)}" %>
        <%= link_to 'Contact', contact_path, class: "nav-item nav-link #{yield(:contact_active)}" %>
      </div>
      <% if(session[:current_user_id]==nil)%>
        <%= link_to 'Register',register_path, class: "btn btn-outline-success pull-xs-right", style: "margin-left:10px"%>
        <%= link_to 'login', login_path, class: "btn btn-outline-success pull-xs-right", style: "margin-left:10px"%>
      <% else %>
        <%= link_to 'logout',logout_path, class: "btn btn-outline-success pull-xs-right", style: "margin-left:10px"%>
        <%= link_to 'User',info_path(), class: "btn btn-outline-success pull-xs-right", style: "margin-left:10px"%>
      <%= form_tag(users_path, method: :get) do %>
      <div class="row">
        <div class="col-lg-3 pull-xs-right">
          <%= text_field_tag :search,nil, placeholder: 'Search friend...', style: "padding-bottom: 7px; padding-top: 3px; padding-left: 4px;"%>
          <%= submit_tag 'Search', :class => 'btn btn-outline-success'%>
        </div>
      </div>
      <% end %>
    <% end %>
  </nav>
  <br>
  <br>
  <div class="container" <%=controller_name%> <%=action_name%>>
    <%= yield %>
  </div>
</body>
</html>

MyStatus/app/views/pages/about.html.erb
<%= provide(:page_title,'About') %>
<%= provide(:about_active,'active') %>

<h3>
	<strong>About</strong>
</h3>

MyStatus/app/views/pages/contact.html.erb
<%= provide(:page_title,'Contact with us') %>
<%= provide(:contact_active,'active') %>

MyStatus/app/views/pages/home.html.erb
<% provide(:page_title, 'Home') %>

MyStatus/app/views/statuses/_form.html.erb
<div class="container" style="margin-bottom: 10px;">
  <%= form_for(status) do |f| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group" style="margin-left: 300px;">
    <%= f.text_area :content, :class => 'form-group', size: '50x3', :style =>'margin-bottom: 0px; ; padding: 5px;' , placeholder: "What on your mind?"%>
  </div>

  <div class="actions">
      <%= f.submit 'Submit' , :class => 'btn btn-primary pull-xs-right', :style =>"margin-right: 330px;" %>
  </div>
<% end %>
</div>

<div class="container">
  <%= render @statuses %>
</div>

MyStatus/app/views/statuses/_status.html.erb
<div class="row card">
	<div class="container" style="margin-top: 5px;">
                <%@user = User.find(status.user_id)%>
                <div class="col-sm-2 card">
                         <div class="text-xs-center"><strong><%= @user.Username%></strong></div>
                         <div class="text-xs-center"><img src="<%=@user.avatar%>" class="img-circle" width="50" height="50"></div>
                </div>
                <div class="col-sm-10">
                        <p class="container modal-body "><%= status.content %></p>
                        <p class="pull-xs-right" style="margin-right: 5px; margin-bottom: 5px;">
                        <% if(status.user_id == session[:current_user_id]) %>
                                <%= link_to 'Edit', edit_status_path(status), class: 'btn btn-primary', style: 'padding: 2px 10px;'%>
                                <%= link_to 'Delete', status, method: :delete, data: { confirm: 'Do you want destroy?' }, class: 'btn btn-danger', style: 'padding: 2px 10px;'%>
                        <%end %>
                        </p>
                </div>
               
                
	</div>
        <div class="container">
                <h6 class="text-muted">Comments</h6>
                <% status.comments.each do |comment|%>
                    <div class="alert alert-success" role="alert" style="padding-top: 10px; padding-bottom: 10px;">
                    <% @temp = User.find(comment.user_id)%>
                      <strong><%= @temp.Username %>: </strong> 
                      <%= comment.body %>
                      <div class="text-xs-right">
                      <% if(comment.user_id==session[:current_user_id] or status.user_id==session[:current_user_id])%>
                          <%= link_to 'Delete',[comment.status, comment], method: :delete, data: { confirm: 'Do you want delete?' },class: 'btn btn-danger', style: 'padding: 2px 10px;'%>
                      <% elsif(comment.status_id==session[:current_user_id]) %>
                          <%= link_to 'Delete',[comment.status, comment], method: :delete, data: { confirm: 'Do you want destroy?' },class: 'btn btn-danger', style: 'padding: 2px 10px;'%>
                        <% end %>
        </div>
                    </div>
                    <div>
                    </div>
                <% end %>

                <%= form_for([status, @status.comments.build]) do |f| %>
                  <p style="margin-bottom: 5px;">
                    <%= f.text_area :body, size:"50x1" %>
                  </p>
                  <p>
                  <%= f.submit 'Comment', :class => 'btn btn-primary', :style => 'padding: 2px 10px; margin-left: 390px;"' %>
                  </p>
                <% end %>
        </div>
</div>

MyStatus/app/views/statuses/_update.html.erb
<div class="container" style="margin-bottom: 10px;">
  <%= form_for(status) do |f| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group" style="margin-left: 300px;">
    <%= f.text_area :content, :class => 'form-group', size: '50x3', :style =>'margin-bottom: 0px;' %>
  </div>

  <div class="actions">
      <%= f.submit 'Submit' , :class => 'btn btn-primary pull-xs-right', :style =>"margin-right: 330px;" %>
  </div>
<% end %>
</div>

MyStatus/app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'update', status: @status %>

MyStatus/app/views/statuses/index.html.erb
<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.id %></td>
        <td><%= status.content %></td>
        <td><%= status.user_id %></td>
        <td><%= link_to 'Show', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status', new_status_path %>

MyStatus/app/views/statuses/new.html.erb
<%= render 'form', status: @status %>

MyStatus/app/views/statuses/show.html.erb
<% provide(:page_title, 'Home') %>


      
<div class="row">
    	<div class="col-sm-3">
         <div>
         <p class="text-xs-center">Anja</p>
 		 <img src="bird.jpg" class="img-circle" style="margin-left: 35px; margin-bottom: 10px;" height="55" width="55" alt="Avatar" >
         </div>
       </div>
    <div class="col-sm-9">
        <div class="card">
          <p>sdfafsdfasdfasdfsdfafsdfasdfasdfsdfafsdfasdfasdfsdfafsdfasdfasdfsdfafsdfasdfasdfsdfafsdfasdfasdfsdfafsdfasdfasdfsdfafsdfasdfasdfsdfafsdfasdfasdfsdfafsdfasdfasdfsdfafsdfasdfasdfsdfafsdfasdfasdfsdfafsdfasdfasdfsdfafsdfasdfasdfsdfafsdfasdfasdf</p>
          <p><%= @status.id%></p>
        </div>
    </div>
</div>     
</div>

MyStatus/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-lg-6">
      <h5>Username</h5>
      <%= f.text_field :Username, :class => 'form-group', :style => 'width: 70%; height:40px' %>

      <h5>Your name</h5>
      <%= f.text_field :Name, :class => 'form-group', :style => 'width: 70%; height:40px' %>

      <h5>Password</h5>
      <%= f.password_field :Password, :class => 'form-group', :style => 'width: 70%; height:40px'%>

      <h5>Birth</h5>
      <%= f.text_field :birth, :class => 'form-group', :style => 'width: 70%; height:40px'%>
    </div>
    <div class="col-lg-6">
      <h5>From</h5>
      <%= f.text_field :from, :class => 'form-group', :style => 'width: 70%; height:40px'%>

      <h5>Word at</h5>
      <%= f.text_field :work_at, :class => 'form-group', :style => 'width: 70%; height:40px'%>

      <h5>Avatar</h5>
      <%= f.text_field :avatar, :class => 'form-group', :style => 'width: 70%; height:40px'%>
    </div>
  </div>
    
  <div class="actions">
      <%= f.submit 'Submit' , :class => 'btn btn-success' %>
  </div>
<% end %>

MyStatus/app/views/users/_user.html.erb
<div class="row card" style="margin-left: 150px; margin-right: 150px;">
  <div class="container" style="margin-bottom: -10px; padding-top: 25px;">
      <div class="col-sm-1">
        <div class="text-xs-center"><img src="<%= user.avatar%>" class="img-circle" width="50" height="50"></div>
      </div>
      <div class="col-sm-11">
        <div ><%= user.Username %></div>
        <div ><%= user.Name %></div>
        <p class="pull-xs-right" style="margin-right: 5px; margin-bottom: 5px;">
          <%= link_to 'Info', user, class: 'btn btn-success', style: 'padding: 2px 10px;' %>
          <% @temp = User.find(session[:current_user_id])%>
          <% if session[:current_user_id] != user.id%>
            <% if @temp.friends.find_by_friend_id(user.id)== nil%>

              <%= link_to "Add Friend", friends_path(:friend_id => user), :method => :post, class: 'btn btn-primary', style: 'padding: 2px 10px;'%>
            <% else %>
              <%= link_to 'Unfriend', {controller: "friends", action: "destroy", id: user.id}, method: "delete", class: 'btn btn-danger', style: 'padding: 2px 10px;' %>
            <% end %>
          <% end %>
        </p>
      </div> 
  </div>
</div>

MyStatus/app/views/users/edit.html.erb
<br>
<br>

<%= render 'form', user: @user %>

MyStatus/app/views/users/index.html.erb
    <%= render @users %>

MyStatus/app/views/users/new.html.erb
<div class="container" style="padding-left: 300px; padding-top: 100px;">
	<%= render 'form', user: @user %>
</div>

MyStatus/app/views/users/show.html.erb
<div class="container">
<div class="row">
	<div class="col-lg-4">
		<img src="<%= @user.avatar %>" class="img-rounded" alt="Cinque Terre" style="width:100%; margin-top: 15px;">
	</div>
	<div class="col-lg-8">
		<div class="alert alert-info" style="width:50%">
			<strong>Username:</strong>
			<%= @user.Username %>
		</div>
		<div class="alert alert-info" style="width:50%">
			<strong>Name:</strong>
			<%= @user.Name %>
		</div>
		<div class="alert alert-info" style="width:50%">
			<strong>Birth:</strong>
			<%= @user.birth %>
		</div>
		<div class="alert alert-info" style="width:50%">
			<strong>From:</strong>
			<%= @user.from %>
		</div>
		<div class="alert alert-info" style="width:50%">
			<strong>Work at:</strong>
			<%= @user.work_at %>
		</div>
	</div>
</div>
<br>
<div class="text-xs-right">
	<a href="/" class="btn btn-info">Back</a>
	<%= link_to 'Edit', edit_user_path(@user), :class => 'btn btn-success' %>
	<%= link_to 'Friend', friends_path, :class => 'btn btn-primary' %>
</div>
</div>